Fixes related to clickhouse and service Port for ingress (#510)
* chore(helm): variablizing clickhouse shards/replica

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* chore(clickhouse): adding new template for clickhouse cluster

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* chore(helm): enable passwordless clickhouse

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* chore(install): check clickhouse is up prior initialization

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* fix(helm): port value for ingress

diff --git a/scripts/helmcharts/openreplay/templates/job.yaml b/scripts/helmcharts/openreplay/templates/job.yaml
--- a/scripts/helmcharts/openreplay/templates/job.yaml
+++ b/scripts/helmcharts/openreplay/templates/job.yaml
@@ -38,6 +38,27 @@ spec:
             git clone https://github.com/openreplay/openreplay /opt/openreplay/openreplay -b {{ .Chart.AppVersion }}
             # Checking variable is empty. Shell independant method.
             if [ "x$ENTERPRISE_EDITION_LICENSE" != "x" ]; then
+              exit_count=0
+              error_connection=1
+
+              while [ $exit_count -le 20 ];do
+                nc -zv clickhouse-openreplay-clickhouse.db.svc.cluster.local 9000 -w 1
+                if [ $? -ne 0 ]; then
+                  echo "[info] clickhouse is not up; retrying in 5 seconds"
+                  sleep 4
+                  exit_count=$(($exit_count+1))
+                  echo $exit_count
+                else
+                  error_connection=0
+                  break
+                fi
+              done
+
+              if [ $error_connection -eq 1 ]; then
+                echo "[error] clickhouse is not running. Check kubectl get po -n db; exiting"
+                exit 100
+              fi
+
               echo "Copying enterprise code"
               cd /opt/openreplay/openreplay 
               cp -rf ee/scripts/* scripts/
