chore(devops): enable clickhouse for foss
Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

diff --git a/scripts/helmcharts/openreplay/templates/job.yaml b/scripts/helmcharts/openreplay/templates/job.yaml
--- a/scripts/helmcharts/openreplay/templates/job.yaml
+++ b/scripts/helmcharts/openreplay/templates/job.yaml
@@ -125,28 +125,28 @@ spec:
             fi
 
             # Checking variable is empty. Shell independant method.
-            if [ "x$ENTERPRISE_EDITION_LICENSE" != "x" ]; then
-              exit_count=0
-              error_connection=1
+            exit_count=0
+            error_connection=1
 
-              while [ $exit_count -le 20 ];do
-                nc -zv {{.Values.global.clickhouse.chHost}} 9000 -w 1
-                if [ $? -ne 0 ]; then
-                  echo "[info] clickhouse is not up; retrying in 5 seconds"
-                  sleep 4
-                  exit_count=$(($exit_count+1))
-                  echo $exit_count
-                else
-                  error_connection=0
-                  break
-                fi
-              done
-
-              if [ $error_connection -eq 1 ]; then
-                echo "[error] clickhouse is not running. Check kubectl get po -n db; exiting"
-                exit 100
+            while [ $exit_count -le 20 ];do
+              nc -zv {{.Values.global.clickhouse.chHost}} 9000 -w 1
+              if [ $? -ne 0 ]; then
+                echo "[info] clickhouse is not up; retrying in 5 seconds"
+                sleep 4
+                exit_count=$(($exit_count+1))
+                echo $exit_count
+              else
+                error_connection=0
+                break
               fi
+            done
 
+            if [ $error_connection -eq 1 ]; then
+              echo "[error] clickhouse is not running. Check kubectl get po -n db; exiting"
+              exit 100
+            fi
+
+            if [ "x$ENTERPRISE_EDITION_LICENSE" != "x" ]; then
               echo "Copying enterprise code"
               cp -rf ee/scripts/* scripts/
             fi
@@ -197,7 +197,6 @@ spec:
               echo For upgrade steps, refer: https://docs.openreplay.com/en/deployment/openreplay-admin/#upgrade-postgresql
               # exit 101
             }
-      {{- if .Values.global.enterpriseEditionLicense }}
       - name: clickhouse-check
         image: clickhouse/clickhouse-server:22.12-alpine
         env:
@@ -246,7 +245,6 @@ spec:
               echo For upgrade steps, refer: https://docs.openreplay.com/en/deployment/openreplay-admin/#upgrade-clickhouse
               # exit 101
             }
-        {{- end}}
         volumeMounts:
           - name: shared
             mountPath: /opt/openreplay
