chore(cli): Installing the cli
Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

diff --git a/scripts/helmcharts/openreplay-cli b/scripts/helmcharts/openreplay-cli
--- a/scripts/helmcharts/openreplay-cli
+++ b/scripts/helmcharts/openreplay-cli
@@ -1,138 +1,162 @@
 #!/bin/bash
+# vim: set ft=sh:
 
-## This script is a helper for managing your OpenReplay instance
+OR_DIR="/var/lib/openreplay"
+APP_NS="${APP_NS:-app}"
+DB_NS="${DB_NS:-app}"
+tmp_dir=$(mktemp -d)
 
-set -eE -o pipefail  # same as: `set -o errexit -o errtrace`
-# Trapping the error
-trap err EXIT
+[[ -d $OR_DIR ]] || {
+  sudo mkdir $OR_DIR
+}
+export PATH=$PATH:/var/lib/openreplay
 
-err() {
-  exit $1
+tools=(
+  zyedidia/eget
+  stern/stern
+  derailed/k9s
+  mikefarah/yq
+  )
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+NC='\033[0m' # No Color
+
+# Checking whether the app exists or we do have to upgade.
+function exists() {
+  which "${1}" &> /dev/null
+  return $?
 }
 
-# make all stderr red
-color()(set -o pipefail;"$@" 2>&1>&3|sed $'s,.*,\e[31m&\e[m,'>&2)3>&1
-
-# color schemes
-# Ansi color code variables
-red="\e[0;91m"
-blue="\e[0;94m"
-expand_bg="\e[K"
-blue_bg="\e[0;104m${expand_bg}"
-red_bg="\e[0;101m${expand_bg}"
-green_bg="\e[0;102m${expand_bg}"
-green="\e[0;92m"
-white="\e[0;97m"
-bold="\e[1m"
-uline="\e[4m"
-reset="\e[0m"
-
-CWD=$pwd
-
-usage()
-{
-clear
-cat <<"EOF"
-  ___                   ____            _
- / _ \ _ __   ___ _ __ |  _ \ ___ _ __ | | __ _ _   _
-| | | | '_ \ / _ \ '_ \| |_) / _ \ '_ \| |/ _` | | | |
-| |_| | |_) |  __/ | | |  _ <  __/ |_) | | (_| | |_| |
- \___/| .__/ \___|_| |_|_| \_\___| .__/|_|\__,_|\__, |
-      |_|                        |_|            |___/
-
-EOF
-
-  echo -e "${green}Usage: [DEBUG=1|SKIP_MIGRAION=1] openreplay-cli [ -h | --help ]
-                  [ -d | --status ]
-                  [ -v | --verbose ]
-                  [ -l | --logs SERVICE ] 
-                  [ -I | --helm-install SERVICE ]
-                  [ -s | --stop SERVICE|all ] 
-                  [ -S | --start SERVICE|all ]
-                  [ -r | --restart SERVICE|all ]"
-  echo -e "${reset}${blue}services: ${services[*]}${reset}"
-  exit 0
-}
-services=( alerts assets chalice clickhouse ender sink storage http integrations ios-proxy db pg redis postgresql )
-
-check() {
-    if ! command -v kubectl &> /dev/null
-    then
-        >&2 echo "Kubectl not found. Please refer https://kubernetes.io/docs/tasks/tools/install-kubectl/ "
-        exit 2
-    fi
-    kubectl cluster-info &> /dev/null
-    if [[ $? -ne 0 ]]; then
-        echo -e "${red}Kubernetes cluster is not accessible.\nPlease check ${bold}KUBECONFIG${reset}${red} env variable is set or ${bold}~/.kube/config exists.${reset}"
-        exit 1
-    fi
-}
-
-stop() {
-    if [[ $1 == "all" ]]; then
-        kubectl scale deployment -n app --replicas=0 --all
-        return
-    fi
-    kubectl scale -n app deployment --replicas=0 $1-openreplay
-}
-
-start() {
-    helm upgrade --install openreplay -n app openreplay -f vars.yaml
-}
-
- 
-restart() {
-    if [[ $1 == "all" ]]; then
-        kubectl rollout restart deployment -n app
-        return
-    fi
-    kubectl rollout restart -n app deployment $1-openreplay
-}
-
-
-helmInstall() {
-  # Adding variables
-  [[ $SKIP_MIGRATION -eq 1 ]] && ARGS="--set skipMigration=true"
-  [[ $DEBUG -eq 1 ]] && ARGS="$ARGS --debug"
-  helm upgrade --install openreplay -n app openreplay -f vars.yaml $ARGS
-}
-
-logs() {
-    check
-    kubectl logs --timestamps -n app -l app.kubernetes.io/name=$1 -f
-}
-
-status() {
-    kubectl get deployment.apps -n app
-}
-
-[[ $# -eq 0 ]] && usage && exit 1
-
-PARSED_ARGUMENTS=$(color getopt -a -n openreplay-cli -o vhds:S:l:r:I --long verbose,help,status,start:,stop:,logs:,restart:,helm-install -- "$@")
-VALID_ARGUMENTS=$?
-if [[ "$VALID_ARGUMENTS" != "0" ]]; then
-  usage
-fi
-
-eval set -- "$PARSED_ARGUMENTS"
-while :
-do
+function log () {
   case "$1" in
-    -v | --verbose) VERBOSE=1    ; shift   ;;
-    -h | --help)    usage        ; shift   ;;
-    -d | --status)  status       ; shift   ;;
-    -I | --helm-install) helmInstall; shift ;;
-    -s | --stop)    stop $2      ; shift 2 ;;
-    -S | --start)   start $2     ; shift 2 ;;
-    -l | --logs)    logs "$2"    ; shift 2 ;;
-    -r | --restart) restart "$2" ; shift 2 ;;
-    # -- means the end of the arguments; drop this, and break out of the while loop
-    --) shift; break ;;
-    # If invalid options were passed, then getopt should have reported an error,
-    # which we checked as VALID_ARGUMENTS when getopt was called...
-    *) echo "Unexpected option: $1 - this should not happen."
-       usage ;;
+    info)
+      shift
+      echo -e "${GREEN}[INFO]" "$@" "${NC}"
+      return
+    ;;
+    debug)
+      shift
+      echo -e "${YELLOW}[DEBUG]" "$@" "${NC}"
+      return
+    ;;
+    err)
+      shift
+      echo -e "${RED}[INFO]" "$@" "${NC}"
+      exit 100
+    ;;
+    *)
+      echo "Not supported log format"
+    ;;
+  esac
+  echo "[Error]" "$@"
+  exit 100
+}
+
+function install_packages() {
+
+  exists eget || {
+    cd "$tmp_dir" || log err "Not able to cd to tmp dir $tmp_dir"
+    curl --version &> /dev/null || log err "curl not found. Please install"
+    curl https://zyedidia.github.io/eget.sh | sh
+    sudo mv eget $OR_DIR
+    cd - || log err "Can't cd to old dir"
+  }
+
+  for package in "${tools[@]}"; do
+    log info Installing "$(awk -F/ '{print $2}' <<< $package)"
+    sudo /var/lib/openreplay/eget -q --upgrade-only --to /var/lib/openreplay "$package"
+  done
+  sudo /var/lib/openreplay/eget -q --to "$OR_DIR" https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz -f helm
+  sudo /var/lib/openreplay/eget -q --to "$OR_DIR" https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
+}
+
+function help() {
+  log debug 'USAGE: openreplay -p[ackages]
+                          -u[pgrade]
+                          -i[nstall]
+                          -s[status]
+                          -l[logs] [app name]
+               App Names: alerts assets assist chalice 
+                          db ender frontend heuristics 
+                          http integrations nginx-controller 
+                          peers sink sourcemapreader storage 
+    '
+  return
+}
+
+function status() {
+  log info OpenReplay Version
+  # awk '(NR<2)' < "$OR_DIR/vars.yaml"
+  awk '/fromVersion/{print $2}' < "${OR_DIR}/vars.yaml"
+  log info Disk Status
+  df -h /var
+  log info Memory Status
+  free -mh
+  log info CPU Status
+  uname -a
+  # Print only the fist line.
+  awk '(NR<2)' < /etc/os-release 
+  echo "CPU Count: $(nproc)"
+  log info Kubernetes Status
+  kubectl version --short
+  log info Openreplay Component Status
+  kubectl get po -n "${APP_NS}"
+  kubectl get po -n "${DB_NS}"
+  return
+}
+
+function upgrade() {
+  # TODO:
+  # 1. store vars.yaml in central place.
+  # 2. While install do we have to clone?
+  # 2. In upgrade you'll have to clone the repo
+  info
+}
+
+# Ref: https://stackoverflow.com/questions/16483119/an-example-of-how-to-use-getopts-in-bash
+while getopts piuhsl: flag
+do
+  case "$flag" in
+    p)
+      log info "Installing Packages"
+      install_packages
+      exit 0
+    ;;
+    i)
+      log info "Installing OpenReplay"
+      sudo cp -f ./openreplay /bin/
+      read -rp "Enter your domain name(openreplay.mycompany.com): " domain_name
+      DOMAIN_NAME=$domain_name bash init.sh
+      sudo cp -f ./vars.yaml "$OR_DIR"
+      exit 0
+    ;;
+    u)
+      log info "Upgrading OpenReplay"
+      sudo mv ./openreplay /bin/
+      upgrade
+      sudo mv ./vars.yaml "$OR_DIR"
+      log info All the configuration has been stored to $OR_DIR/vars.yaml file
+      exit 0
+    ;;
+    l)
+      # Skipping double quotes because we want globbing. For example
+      # ./openreplay -l "chalice --tail 10"
+      stern -n "${LOG_NS:-$APP_NS}" ${OPTARG}
+      exit 0
+    ;;
+    s)
+      log info "Checking OpenReplay Components Status\n"
+      status
+      exit 0
+    ;;
+    h|*)
+      help
+      exit 0
+    ;;
   esac
 done
+shift $((OPTIND-1))
 
-[[ $VERBOSE -eq 1 ]] && set -x || true
+[ $# -eq 0 ] && help
