Update PR env creation with latest requirements (#1658)
* fixesss

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* fix pr env variable

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* enble debugging

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

* Automatically take PR number from branch

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

---------

Signed-off-by: rjshrjndrn <rjshrjndrn@gmail.com>

diff --git a/.github/workflows/pr-env.yaml b/.github/workflows/pr-env.yaml
--- a/.github/workflows/pr-env.yaml
+++ b/.github/workflows/pr-env.yaml
@@ -1,15 +1,52 @@
 name: PR-Deployment
 
 on:
-  pull_request:
-    types: [opened, reopened]
+  workflow_dispatch:
+    inputs:
+      build_service:
+        description: 'Name of a single service to build(in small letters). "backend:all" to build complete backend'
+        required: true
+        default: 'frontend'
+      env_flavour:
+        description: 'Which env to build. Values: foss/ee'
+        required: false
+        default: 'foss'
 
 jobs:
   create-vcluster-pr:
     runs-on: ubuntu-latest
+    env:
+      build_service: ${{ github.event.inputs.build_service }}
+      env_flavour: ${{ github.event.inputs.env_flavour }}
     steps:
     - name: Checkout Code
       uses: actions/checkout@v2
+    - name: Setting up env variables
+      run: |
+        # Fetching PR details
+        PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls" \
+            | jq -r --arg BRANCH "${{ github.ref_name }}" '.[] | select(.head.ref==$BRANCH)')
+
+        # Extracting PR number
+        PR_NUMBER=$(echo "$PR_DATA" | jq -r '.number' | head -n 1)
+        if [-z $PR_NUMBER]; then
+          echo "No PR found for ${{ github.ref_name}}"
+          exit 100
+        fi
+
+        echo "PR_NUMBER_PRE=$PR_NUMBER" >> $GITHUB_ENV
+        PR_NUMBER=pr-$PR_NUMBER
+        if [ $env_flavour == "ee" ]; then
+          PR_NUMBER=$PR_NUMBER-ee
+        fi
+        echo "PR number: $PR_NUMBER"
+        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+
+        # Extracting PR status (open, closed, merged)
+        PR_STATUS=$(echo "$PR_DATA" | jq -r '.state' | head -n 1)
+        echo "PR status: $PR_STATUS"
+        echo "PR_STATUS=$PR_STATUS" >> $GITHUB_ENV
     - name: Install vCluster CLI
       run: |
         # Replace with the command to install vCluster CLI
@@ -21,26 +58,45 @@ jobs:
         kubeconfig: ${{ secrets.PR_KUBECONFIG }} # Use content of kubeconfig in secret.
       id: setcontext
 
+    - name: Check existing vcluster
+      id: vcluster_exists
+      continue-on-error: true
+      run: |
+        if [ ! $(vcluster list | grep $PR_NUMBER) ]; then
+          echo "failed state"
+          echo "::set-output name=failed::true"
+          exit 100
+        fi
+        DOMAIN_NAME=${PR_NUMBER}-vcluster.${{ secrets.OR_PR_DOMAIN_NAME }}
+        vcluster connect ${PR_NUMBER}-vcluster --update-current=false --server=https://$DOMAIN_NAME
+        mv kubeconfig.yaml /tmp/kubeconfig.yaml
 
     - name: Get LoadBalancer IP
+      if: steps.vcluster_exists.outputs.failed == 'true'
       id: lb-ip
       run: |
         LB_IP=$(kubectl get svc ingress-ingress-nginx-controller -n default -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
         echo "::set-output name=ip::$LB_IP"
 
     - name: Create vCluster
+      if: steps.vcluster_exists.outputs.failed == 'true'
       run: |
-        PR_NUMBER=$(echo ${{ github.event.pull_request.number }} || echo $GITHUB_RUN_NUMBER)
         # Replace with the actual command to create a vCluster
-        cd openreplay/scripts/pr-env/vcluster
-        bash create.sh pr-${PR_NUMBER}.${{ secrets.OR_PR_DOMAIN_NAME }}
+        pwd
+        cd scripts/pr-env/
+        bash create.sh ${PR_NUMBER}.${{ secrets.OR_PR_DOMAIN_NAME }}
         cp kubeconfig.yaml /tmp/
 
     - name: Update AWS Route53 Record
+      if: steps.vcluster_exists.outputs.failed == 'true'
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.OR_PR_AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.OR_PR_AWS_SECRET_ACCESS_KEY }}
+        AWS_DEFAULT_REGION: ${{ secrets.OR_PR_AWS_DEFAULT_REGION }}
       run: |
-        PR_NUMBER=$(echo ${{ github.event.pull_request.number }} || echo $GITHUB_RUN_NUMBER)
         DOMAIN_NAME_1=$PR_NUMBER-vcluster.${{ secrets.OR_PR_DOMAIN_NAME }}
         DOMAIN_NAME_2=$PR_NUMBER.${{ secrets.OR_PR_DOMAIN_NAME }}
+
         cat <<EOF > route53-changes.json
         {
           "Comment": "Create record set for VCluster",
@@ -66,14 +122,23 @@ jobs:
           ]
         }
         EOF
+        #
+        NEW_IP=${{ steps.lb-ip.outputs.ip }} 
 
-        aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.OR_PR_HOSTED_ZONE_ID }} --change-batch file://route53-changes.json
+        # Get the current IP address associated with the domain
+        CURRENT_IP=$(dig +short $DOMAIN_NAME_1 @1.1.1.1)
+        echo "current ip: $CURRENT_IP"
+        # Check if the domain has no IP association or if the IPs are different
+        if [ -z "$CURRENT_IP" ] || [ "$CURRENT_IP" != "$NEW_IP" ]; then
+          aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.OR_PR_HOSTED_ZONE_ID }} --change-batch file://route53-changes.json
+        fi
+
 
     - name: Wait for DNS Propagation
+      if: steps.vcluster_exists.outputs.failed == 'true'
       env:
         EXPECTED_IP: ${{ steps.lb-ip.outputs.ip }}
       run: |
-        PR_NUMBER=$(echo ${{ github.event.pull_request.number }} || echo $GITHUB_RUN_NUMBER)
         DOMAIN_NAME_1="$PR_NUMBER-vcluster.${{ secrets.OR_PR_DOMAIN_NAME }}"
         MAX_ATTEMPTS=30
         attempt=1
@@ -95,25 +160,63 @@ jobs:
         fi
 
     - name: Install openreplay
+      if: steps.vcluster_exists.outputs.failed == 'true'
       env:
         KUBECONFIG: /tmp/kubeconfig.yaml
       run: |
-        PR_NUMBER=$(echo ${{ github.event.pull_request.number }} || echo $GITHUB_RUN_NUMBER)
         DOMAIN_NAME=$PR_NUMBER.${{ secrets.OR_PR_DOMAIN_NAME }}
-        cd openreplay/scripts/helmcharts
+        cd scripts/helmcharts
         sed -i "s/domainName: \"\"/domainName: \"${DOMAIN_NAME}\"/g" vars.yaml
-        helm upgrade -i databases -n db ./databases -f vars.yaml --create-namespace --wait --debug
-        helm upgrade -i openreplay -n app ./openreplay -f vars.yaml --create-namespace --set ingress-nginx.enabled=false -f ../pr-env/resources.yaml --wait --debug
+        helm upgrade -i databases -n db ./databases -f vars.yaml --create-namespace --wait
+        helm upgrade -i openreplay -n app ./openreplay -f vars.yaml --create-namespace --set ingress-nginx.enabled=false -f ../pr-env/resources.yaml --wait
 
-    - name: Send Slack Message
+    - name: Sent results to slack
       env:
-        SLACK_URL: ${{ secrets.OR_PR_SLACK_URL }}
+        SLACK_BOT_TOKEN: ${{ secrets.OR_PR_SLACK_BOT_TOKEN }}
+        SLACK_CHANNEL: ${{ secrets.OR_PR_SLACK_CHANNEL }}
       run: |
-        PR_NUMBER=$(echo ${{ github.event.pull_request.number }} || echo $GITHUB_RUN_NUMBER)
-        curl -X POST -H 'Content-type: application/json' --data '{"text":"PR Number: '$PR_NUMBER'\nVCluster: '$PR_NUMBER-vcluster.${{ secrets.OR_PR_DOMAIN_NAME }}'\nGenerated VCluster Kubeconfig File"}' $SLACK_URL
+        echo hi ${{ steps.vcluster_exists.outputs.failed }}
+        DOMAIN_NAME=https://$PR_NUMBER.${{ secrets.OR_PR_DOMAIN_NAME }}
+
+        # Variables
+        PR_NUMBER=https://github.com/${{ github.repository }}/pull/${PR_NUMBER_PRE}
+        BRANCH_NAME=${{ github.ref_name }}
+        ORIGIN=$DOMAIN_NAME
+        ASSETS_HOST=$DOMAIN_NAME/assets
+        API_EDP=$DOMAIN_NAME/api
+        INGEST_POINT=$DOMAIN_NAME/ingest
+
+        # File to be uploaded
+        FILE_PATH="/tmp/kubeconfig.yaml"
+        if [! -f $FILE_PATH ]; then
+          echo "Kubeconfig file not found: $FILE_PATH"
+          exit 100
+        fi
+
+        # Form the message payload
+        PAYLOAD=$(cat <<EOF
+        {
+            "channel": "$SLACK_CHANNEL",
+            "text": "Deployment Information:\n- PR#: $PR_NUMBER\n- PR Status: $PR_STATUS\n- Branch Name: $BRANCH_NAME\n- Origin: $ORIGIN\n- Assets Host: $ASSETS_HOST\n- API Endpoint: $API_EDP\n- Ingest Point: $INGEST_POINT\n- To use the cluster: download the following file and run the following commands, \n  export KUBECONFIG=/path/to/kubeconfig.yaml\n  k9s"
+        }
+        EOF
+        )
+
+        # Send the message to Slack
+        curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H 'Content-type: application/json' --data "$PAYLOAD" https://slack.com/api/chat.postMessage > /dev/null
+
+        # Upload the file to Slack
+        curl -F file=@"$FILE_PATH" -F channels="$SLACK_CHANNEL" -F token="$SLACK_BOT_TOKEN" https://slack.com/api/files.upload > /dev/null
 
     # - name: Cleanup
     #   if: always()
     #   run: |
     #     # Add any cleanup commands if necessary
 
+    # - name: Debug Job
+    #   if: failure()
+    #   uses: mxschmitt/action-tmate@v3
+    #   env:
+    #     DOCKER_REPO: ${{ secrets.OSS_REGISTRY_URL }}
+    #     IMAGE_TAG: ${{ github.sha }}
+    #     ENVIRONMENT: staging
